[package]
name = "gingster"
description = "Gin Rummy playing engine"
version = "0.1.5"
authors = ["serpent-code"]
edition = "2018"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
